spring:
    application:
        name : edu3

    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:mysql://10.0.1.2:3306/basic} #jdbc:mysql://localhost:3306/basic
        username: ${SPRING_DATASOURCE_USERNAME:test-root} #test-root
        password: ${SPRING_DATASOURCE_PASSWORD:admin1234} #admin1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    security:
      oauth2:
        client:
          registration:
            kakao:
              client-id: 8bab7eeca5ca523c152a6f7ebfdc0939                     # RestAPI 키
              client-secret: ps1VJogeuE9h0jLneDyEAfofKs1A4rXk                 # 비즈니스 인증 키
              redirect-uri: http://35.216.18.100:8080/login/oauth2/code/kakao     
              authorization-grant-type: authorization_code    
              client-authentication-method: client_secret_post
              client-name: Kakao
              scope:
                - profile_nickname
                - profile_image
                - account_email
            naver:
              client-id: vir_dd4yhwTuoXDUhbjZ
              client-secret:  uzI9FLyoUR
              redirect-uri: http://35.216.18.100:8080/login/oauth2/code/naver
              authorization-grant-type: authorization_code
              client-name: Naver
              scope:
                - name
                - email
          provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id
            naver:
              authorization-uri: https://nid.naver.com/oauth2.0/authorize
              token-uri: https://nid.naver.com/oauth2.0/token
              user-info-uri: https://openapi.naver.com/v1/nid/me
              user-name-attribute: response

server:
  port: 8080
  servlet:
    context-path: /

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.ict.edu3

# 비밀키 사용(32바이트길이)  
# 1 시간 = 1000ms * 60 * 60 ;
jwt:
  secret : "abcdASDF1234abcdQWER0987poiuPOIU"
  access-token-validity: 900000 
  refresh-token-validity: 604800000
  expiration : 3600000 

